<?php

declare(strict_types=1);

// Prepares the browser tests, and cleans up after them. Playwright runs it:
//
//     php tests/e2e/setup.php          makes the database and the config
//     php tests/e2e/setup.php drop     drops the database and the config
//
// It uses the first server named in TEST_MYSQL_* or TEST_PGSQL_*, like the API
// tests, and a database called sqlaris_e2e, so that name must be free there.

require __DIR__.'/../../src/lib.php';

const E2E_DATABASE = 'sqlaris_e2e';
const E2E_CONFIG = 'sqlaris-e2e-config.php';

const E2E_FIXTURES = [
    'mysql' => [
        'create table people (id int auto_increment primary key, name varchar(100) not null, age int)',
        "insert into people (name, age) values ('Ada Lovelace', 36), ('Grace Hopper', 85), ('Alan Turing', 41)",
    ],
    'pgsql' => [
        'create table people (id integer generated by default as identity primary key, name text not null, age integer)',
        "insert into people (name, age) values ('Ada Lovelace', 36), ('Grace Hopper', 85), ('Alan Turing', 41)",
    ],
];

$env = dbv_env_file(__DIR__.'/../.env') + getenv();
$settings = null;

foreach (['MYSQL' => ['mysql', 3306, 'root'], 'PGSQL' => ['pgsql', 5432, 'postgres']] as $prefix => [$driver, $port, $user]) {
    if ((string) ($env["TEST_{$prefix}_HOST"] ?? '') !== '') {
        $settings = [
            'label' => $driver,
            'driver' => $driver,
            'host' => (string) $env["TEST_{$prefix}_HOST"],
            'port' => (int) ($env["TEST_{$prefix}_PORT"] ?? $port),
            'username' => (string) ($env["TEST_{$prefix}_USERNAME"] ?? $user),
            'password' => (string) ($env["TEST_{$prefix}_PASSWORD"] ?? ''),
            'database' => 'postgres',
            'only' => [E2E_DATABASE],
        ];

        break;
    }
}

if ($settings === null) {
    fwrite(STDERR, "The browser tests need a database server. Set TEST_MYSQL_HOST or TEST_PGSQL_HOST, as for the API tests.\n");
    exit(1);
}

$class = DBV_DRIVERS[$settings['driver']];
$admin = $class::connect($settings, $settings['driver'] === 'pgsql' ? 'postgres' : null);
$config = sys_get_temp_dir().'/'.E2E_CONFIG;

if ($settings['driver'] === 'pgsql') {
    // The page's own connections may still be open, so they are closed first.
    $admin->exec("select pg_terminate_backend(pid) from pg_stat_activity where datname = '".E2E_DATABASE."' and pid <> pg_backend_pid()");
}

$admin->exec('drop database if exists '.E2E_DATABASE);

if (($argv[1] ?? '') === 'drop') {
    @unlink($config);
    exit(0);
}

$admin->exec('create database '.E2E_DATABASE);
$pdo = $class::connect($settings, E2E_DATABASE);

foreach (E2E_FIXTURES[$settings['driver']] as $statement) {
    $pdo->exec($statement);
}

// The sign-in the specs use. It only exists in this temporary file, for a server on 127.0.0.1.
file_put_contents($config, '<?php return '.var_export([
    'username' => 'tester',
    'password' => 'e2e-password',
    'servers' => ['e2e' => $settings],
], true).";\n");
