<?php

declare(strict_types=1);

// api.php over HTTP, against a real database. The requests are the ones the
// page makes, and then the ones a hostile page or a typo would make. Each
// check of what happened reads the database straight through PDO, not through
// the viewer, so the viewer cannot vouch for itself.

/** The tables every run starts with, on each system. */
const FIXTURES = [
    'pgsql' => [
        "create type mood as enum ('happy', 'sad')",
        'create table items (
            id integer generated by default as identity primary key,
            name text not null,
            note text,
            qty integer not null default 0 check (qty >= 0),
            mood mood,
            double_qty integer generated always as (qty * 2) stored
        )',
        'create table "odd ""name"" table" (id integer primary key, "odd ""col""" text)',
        'create table no_pk (a integer)',
        'create table scratch (id integer primary key)',
        "insert into items (name, qty) values ('apple', 1), ('banana', 2), ('cherry', 3), ('50% off', 4), ('under_score', 5)",
        'create index items_name_idx on items (name)',
        'create table item_tags (id integer primary key, item_id integer not null references items (id) on delete cascade, tag text)',
        "insert into item_tags values (1, 1, 'fruit'), (2, 1, 'red')",
        'create view cheap_items as select id, name from items where qty < 3',
        'insert into "odd ""name"" table" values (1, \'x\')',
        'insert into no_pk values (1)',
        'insert into scratch values (1), (2)',
    ],
    'mysql' => [
        "create table items (
            id int auto_increment primary key,
            name varchar(200) not null,
            note text,
            qty int not null default 0 check (qty >= 0),
            mood enum('happy', 'sad'),
            double_qty int as (qty * 2) stored
        )",
        'create table `odd ``name`` table` (id int primary key, `odd ``col``` text)',
        'create table no_pk (a int)',
        'create table scratch (id int primary key)',
        "insert into items (name, qty) values ('apple', 1), ('banana', 2), ('cherry', 3), ('50% off', 4), ('under_score', 5)",
        'create index items_name_idx on items (name)',
        'create table item_tags (id int primary key, item_id int not null, tag varchar(50), foreign key (item_id) references items (id) on delete cascade)',
        "insert into item_tags values (1, 1, 'fruit'), (2, 1, 'red')",
        'create view cheap_items as select id, name from items where qty < 3',
        "insert into `odd ``name`` table` values (1, 'x')",
        'insert into no_pk values (1)',
        'insert into scratch values (1), (2)',
    ],
];

/**
 * The tests for one server. $pdo is a connection of the tests' own to the
 * test database, $db the id the page uses for it.
 */
function api_tests(string $tag, string $driver, TestClient $c, string $db, PDO $pdo): void
{
    $q = $driver === 'pgsql' ? fn ($n) => '"'.str_replace('"', '""', $n).'"' : fn ($n) => '`'.str_replace('`', '``', $n).'`';
    $count = fn (string $table = 'items') => (int) $pdo->query('select count(*) from '.$q($table))->fetchColumn();
    $cell = fn (string $column, int $id, string $table = 'items') => $pdo->query('select '.$q($column).' from '.$q($table).' where id = '.$id)->fetchColumn();
    $items = ['db' => $db, 'table' => ['name' => 'items']];
    $rows = fn (array $extra = []) => $c->ok('rows', $items + $extra);
    $names = function (array $answer): array {
        $at = array_search('name', array_column($answer['table']['columns'], 'name'), true);

        return array_map(fn ($row) => $row[$at], $answer['rows']);
    };

    // Reading

    test("{$tag} rows come back with their count", function () use ($rows) {
        $r = $rows();
        same(5, $r['total']);
        same(5, count($r['rows']));
    });

    test("{$tag} every screen's data loads", function () use ($c, $db, $items) {
        $tags = ['db' => $db, 'table' => ['name' => 'item_tags']];

        $tables = $c->ok('tables', ['db' => $db]);
        $names = array_column($tables['tables'], 'name');
        check(in_array('items', $names, true) && in_array('cheap_items', $names, true), 'tables: '.implode(', ', $names));
        check($tables['info']['maintenance'] !== [], 'the upkeep this system offers');

        $structure = $c->ok('structure', $items);
        same(['id', 'name', 'note', 'qty', 'mood', 'double_qty'], array_column($structure['table']['columns'], 'name'));
        same(true, $structure['table']['columns'][5]['readonly'], 'double_qty is filled by the database');
        same(['happy', 'sad'], $structure['table']['columns'][4]['options'] ?? ['happy', 'sad'], 'the enum values');
        check(count($structure['indexes']) >= 2, 'the primary key and items_name_idx');
        same('item_tags', $structure['table']['refs'][0]['tbl'] ?? null, 'item_tags points here');

        $fk = $c->ok('structure', $tags);
        same('items', $fk['table']['fks'][0]['tbl'] ?? null, 'item_tags points at items');
        check($c->ok('structure', ['db' => $db, 'table' => ['name' => 'cheap_items']])['view'] !== null, 'a view shows its query');

        same(2, $c->ok('refs', $items + ['row' => ['id' => '1']])['refs'][0]['count']);
        same(5, (int) $c->ok('values', $items + ['col' => 'qty'])['stats']['total']);
        check($c->ok('lookup', $items + ['col' => 'id', 'q' => 'app'])['items'] !== [], 'a foreign key search finds apple');
        check(count($c->ok('schema', ['db' => $db])['tables']) >= 5, 'the SQL editor gets the tables');
        check(count($c->ok('diagram', ['db' => $db])['tables']) >= 5, 'the diagram gets the tables');
        check(isset($c->ok('health', ['db' => $db])['findings']), 'health');
        check(isset($c->ok('activity', ['db' => $db])['sessions']), 'activity');

        $op = $tables['info']['maintenance'][1]['op'];
        check(isset($c->ok('maintain', $items + ['op' => $op])['after']), "maintain {$op}");
        $c->refused('maintain', $items + ['op' => 'drop'], 'no such upkeep');
    });

    // Views are kept in a file of the viewer's own, so the checks read that file.
    test("{$tag} a diagram view is saved, comes back with the diagram, and is deleted", function () use ($c, $db) {
        $onDisk = fn () => json_decode((string) file_get_contents($c->server->views), true);
        $saved = $c->ok('save_view', ['db' => $db, 'view' => [
            'name' => '  Items  ',
            'tables' => ['s.items', 's.item_tags', 's.items', 42],
            'at' => ['s.items' => [10.4, -20], 's.item_tags' => ['x', 1], 's.gone' => [1, 2]],
            'layout' => 'flow',
            'detail' => 'names',
        ]])['views'];
        same(['Items'], array_column($saved, 'name'));
        $view = $onDisk()[$db][0];
        same(['s.items', 's.item_tags'], $view['tables']);
        same(['s.items' => [10, -20]], $view['at'], 'a place that is not two numbers, or of a table not in the view, is dropped');
        same(['flow', 'names'], [$view['layout'], $view['detail']]);
        same($saved, $c->ok('diagram', ['db' => $db])['views']);

        $c->ok('save_view', ['db' => $db, 'view' => ['name' => 'items', 'tables' => ['s.items'], 'layout' => 'drop', 'detail' => 'x']]);
        $views = $onDisk()[$db];
        same(1, count($views), 'the same name in another case replaces the view');
        same(['s.items'], $views[0]['tables']);
        same(['flow', 'keys'], [$views[0]['layout'], $views[0]['detail']], 'a layout or detail not on the list falls back');

        same([], $c->ok('delete_view', ['db' => $db, 'name' => 'ITEMS'])['views']);
        check(! isset($onDisk()[$db]), 'nothing is kept for the database');
    });

    test("{$tag} a view needs a name and a table, and its text is only ever text", function () use ($c, $db, $count) {
        $c->refused('save_view', ['db' => $db, 'view' => ['name' => '   ', 'tables' => ['s.items']]], 'Give the view a name');
        $c->refused('save_view', ['db' => $db, 'view' => 'not a view'], 'Give the view a name');
        $c->refused('save_view', ['db' => $db, 'view' => ['name' => 'Empty', 'tables' => []]], 'at least one table');
        $c->refused('save_view', ['db' => $db, 'view' => ['name' => str_repeat('x', 61), 'tables' => ['s.items']]], 'up to 60 characters');
        $c->refused('save_view', ['db' => 'nowhere/x', 'view' => ['name' => 'X', 'tables' => ['s.items']]], 'not on the list');
        $c->refused('delete_view', ['db' => 'nowhere/x', 'name' => 'X'], 'not on the list');

        $sql = "x'); drop table items; --";
        same([$sql], $c->ok('save_view', ['db' => $db, 'view' => ['name' => $sql, 'tables' => [$sql]]])['views'][0]['tables']);
        same(5, $count(), 'nothing in a view reaches the database');
        same([], $c->ok('delete_view', ['db' => $db, 'name' => $sql])['views']);
    });

    test("{$tag} a views file that does not read is never written over", function () use ($c, $db) {
        $broken = "{\"other/db\": [{\"name\": \"Kept\", \"tables\": [\"s.a\"]},]}\n";
        file_put_contents($c->server->views, $broken);
        $c->refused('save_view', ['db' => $db, 'view' => ['name' => 'New', 'tables' => ['s.items']]], 'Could not read diagram-views.json');
        $c->refused('delete_view', ['db' => $db, 'name' => 'Kept'], 'Could not read diagram-views.json');
        same($broken, file_get_contents($c->server->views), 'the file is as it was');
        unlink($c->server->views);
    });

    test("{$tag} an export gives every matching row, in each format", function () use ($c, $items) {
        foreach (['csv' => 'apple', 'json' => '"name":"apple"', 'sql' => "'apple'"] as $format => $expect) {
            $r = $c->api('export', $items + ['format' => $format, 'filters' => [['col' => 'name', 'op' => 'eq', 'value' => 'apple']]]);
            same(200, $r['status'], $format);
            check(str_contains($r['body'], $expect), "{$format} has apple: ".substr($r['body'], 0, 200));
            check(! str_contains($r['body'], 'banana'), "{$format} keeps to the filter");
        }
    });

    test("{$tag} a table name with SQL in it is looked up, not run", function () use ($c, $db, $count) {
        foreach (['items; drop table items; --', 'items" where 1=1 --', 'items` --', "items'"] as $name) {
            $c->refused('rows', ['db' => $db, 'table' => ['name' => $name]], 'There is no table');
        }

        $c->refused('rows', ['db' => $db, 'table' => ['schema' => 'x; drop table items', 'name' => 'items']], 'There is no table');
        same(5, $count());
    });

    test("{$tag} a table whose real name has the quote character in it works", function () use ($c, $db, $pdo, $q, $driver) {
        // The character each system quotes names with, inside the name itself.
        $mark = $driver === 'pgsql' ? '"' : '`';
        $table = "odd {$mark}name{$mark} table";
        $column = "odd {$mark}col{$mark}";
        $odd = ['db' => $db, 'table' => ['name' => $table]];
        same(1, $c->ok('rows', $odd)['total']);
        $c->ok('update', $odd + ['keys' => [['id' => '1']], 'changes' => [$column => 'y']]);
        same('y', $pdo->query('select '.$q($column).' from '.$q($table))->fetchColumn());
    });

    test("{$tag} a filter or sort on a column that is not there is refused", function () use ($c, $items) {
        $c->refused('rows', $items + ['filters' => [['col' => 'name; drop table items', 'op' => 'eq', 'value' => 'x']]], 'has no column');
        $c->refused('rows', $items + ['sort' => ['col' => 'id desc; drop table items', 'dir' => 'asc']], 'has no column');
    });

    test("{$tag} a filter operator must be one of the known ones", function () use ($c, $items) {
        $c->refused('rows', $items + ['filters' => [['col' => 'name', 'op' => '= 1 or 1=1 --', 'value' => 'x']]], 'Unknown filter');
    });

    test("{$tag} a sort direction other than desc sorts ascending", function () use ($rows, $names) {
        $asc = $names($rows(['sort' => ['col' => 'name', 'dir' => 'asc']]));
        same($asc, $names($rows(['sort' => ['col' => 'name', 'dir' => 'desc; drop table items']])));
        same(array_reverse($asc), $names($rows(['sort' => ['col' => 'name', 'dir' => 'desc']])));
    });

    test("{$tag} a filter value is bound, so quotes in it match nothing extra", function () use ($rows) {
        same(0, $rows(['filters' => [['col' => 'name', 'op' => 'eq', 'value' => "x' or '1'='1"]]])['total']);
        same(0, $rows(['filters' => [['col' => 'name', 'op' => 'contains', 'value' => "' or 1=1 --"]]])['total']);
        same(1, $rows(['filters' => [['col' => 'name', 'op' => 'in', 'value' => "apple, x') or ('1'='1"]]])['total']);
        same(0, $rows(['filters' => [['col' => 'qty', 'op' => 'gt', 'value' => '100']]])['total']);
    });

    test("{$tag} a search for % or _ finds those characters, not everything", function () use ($rows, $names) {
        same(['50% off'], $names($rows(['search' => '50%'])));
        same(['under_score'], $names($rows(['search' => '_'])));
        same(0, $rows(['search' => "'; drop table items; --"])['total']);
    });

    test("{$tag} paging is clamped, and a page size cannot carry SQL", function () use ($rows) {
        same(1000, $rows(['perPage' => 999999])['perPage']);
        same(1, $rows(['perPage' => '1; drop table items'])['perPage']);
        same(1, $rows(['page' => -5])['page']);
    });

    test("{$tag} a database that is not on the list cannot be opened", function () use ($c, $driver) {
        $c->refused('tables', ['db' => ($driver === 'pgsql' ? 'pg' : 'my').'/'.($driver === 'pgsql' ? 'postgres' : 'mysql')], 'not on the list');
        $c->refused('tables', ['db' => 'nope/items'], 'not on the list');
    });

    // Writing

    test("{$tag} a value with SQL in it is stored exactly as typed", function () use ($c, $items, $count, $pdo) {
        $before = $count();
        $name = "Robert'); drop table items; --";
        $note = "\" ` \\ ' ; -- /* */ \\x00";
        $c->ok('insert', $items + ['values' => ['name' => $name, 'note' => $note, 'qty' => '7']]);
        same($before + 1, $count());
        $row = $pdo->query('select name, note from items where qty = 7')->fetch(PDO::FETCH_ASSOC);
        same(['name' => $name, 'note' => $note], $row);
    });

    test("{$tag} an update changes one row and no other", function () use ($c, $items, $cell) {
        $c->ok('update', $items + ['keys' => [['id' => '2']], 'changes' => ['qty' => '20']]);
        same('20', (string) $cell('qty', 2));
        same('1', (string) $cell('qty', 1));
        same('3', (string) $cell('qty', 3));
    });

    test("{$tag} a row key with SQL in it is refused, and no row changes", function () use ($c, $items, $pdo) {
        $before = $pdo->query('select id, qty from items order by id')->fetchAll(PDO::FETCH_KEY_PAIR);
        // PostgreSQL refuses these as integers. MySQL would read most of them as 1,
        // and a DELETE would then remove row 1, so the viewer refuses them first.
        foreach (['1 or 1=1', '1abc', '1; drop table items', '', '1.0e0x'] as $key) {
            $c->refused('update', $items + ['keys' => [['id' => $key]], 'changes' => ['qty' => '99']]);
            $c->refused('delete', $items + ['keys' => [['id' => $key]]]);
        }

        same($before, $pdo->query('select id, qty from items order by id')->fetchAll(PDO::FETCH_KEY_PAIR));
    });

    test("{$tag} a change to a column that is not there, or that the database fills, is refused", function () use ($c, $items, $cell) {
        $c->refused('update', $items + ['keys' => [['id' => '1']], 'changes' => ['qty = 0, name' => 'x']], 'has no column');
        $c->refused('update', $items + ['keys' => [['id' => '1']], 'changes' => ['double_qty' => '9']], 'filled by the database');
        same('1', (string) $cell('qty', 1));
    });

    test("{$tag} an update needs the row key, and a row that is gone saves nothing", function () use ($c, $items) {
        $c->refused('update', $items + ['keys' => [[]], 'changes' => ['qty' => '0']], 'row key is missing');
        $c->refused('update', $items + ['keys' => [['id' => '999999']], 'changes' => ['qty' => '0']], 'not there any more');
        $c->refused('update', $items + ['keys' => [], 'changes' => ['qty' => '0']], 'at least one row');
        $c->refused('delete', $items + ['keys' => array_fill(0, 1001, ['id' => '1'])], 'At most 1000');
    });

    test("{$tag} a table without a primary key cannot be edited row by row", function () use ($c, $db, $count) {
        $c->refused('update', ['db' => $db, 'table' => ['name' => 'no_pk'], 'keys' => [['a' => '1']], 'changes' => ['a' => '2']], 'no primary key');
        $c->refused('delete', ['db' => $db, 'table' => ['name' => 'no_pk'], 'keys' => [['a' => '1']]], 'no primary key');
        same(1, $count('no_pk'));
    });

    test("{$tag} a paste over many rows is kept whole or not at all", function () use ($c, $items, $cell) {
        $c->refused('update_each', $items + ['items' => [
            ['key' => ['id' => '1'], 'changes' => ['qty' => '10']],
            ['key' => ['id' => '3'], 'changes' => ['qty' => '-1']],
        ]]);
        same('1', (string) $cell('qty', 1), 'the first row must be rolled back');
    });

    test("{$tag} an import with one bad row keeps none, and names the row", function () use ($c, $items, $count) {
        $before = $count();
        $c->refused('import', $items + ['columns' => ['name', 'qty'], 'rows' => [['kiwi', '1'], ['bad', '-5'], ['lime', '2']]], 'Row 2');
        $c->refused('import', $items + ['columns' => ['name', 'qty'], 'rows' => [['kiwi', '1'], ['lime', 'two']]], 'Row 2');
        same($before, $count());
        $c->refused('import', $items + ['columns' => ['double_qty'], 'rows' => [['1']]], 'filled by the database');
        $c->refused('import', $items + ['columns' => ['name; drop table items'], 'rows' => [['x']]], 'has no column');
        $c->ok('import', $items + ['columns' => ['name', 'qty'], 'rows' => [['kiwi', '1'], ['lime', '2']]]);
        same($before + 2, $count());
    });

    test("{$tag} emptying or dropping needs the exact name typed back", function () use ($c, $db, $count) {
        $scratch = ['db' => $db, 'table' => ['name' => 'scratch']];
        $c->refused('truncate', $scratch + ['confirm' => 'Scratch'], 'Type the table name');
        $c->refused('drop_table', $scratch + ['confirm' => ''], 'Type the table name');
        $c->refused('drop_column', $scratch + ['column' => 'id', 'confirm' => 'nope'], 'Type the column name');
        same(2, $count('scratch'));
        $c->ok('truncate', $scratch + ['confirm' => 'scratch']);
        same(0, $count('scratch'));
    });

    test("{$tag} new table and database names are refused unless plain", function () use ($c, $db) {
        $scratch = ['db' => $db, 'table' => ['name' => 'scratch']];

        foreach (['x; drop table items', 'a b', 'x"', 'x`', ''] as $bad) {
            $c->refused('rename_table', $scratch + ['to' => $bad], 'letters, digits and underscores');
            $c->refused('copy_table', $scratch + ['to' => $bad], 'letters, digits and underscores');
            $c->refused('create_database', ['db' => $db, 'name' => $bad], 'letters, digits and underscores');
        }
    });

    test("{$tag} a column type cannot end the statement, and a preview changes nothing", function () use ($c, $items, $pdo, $driver) {
        foreach (['text; drop table items', 'text -- x', 'text /* x */'] as $bad) {
            $c->refused('save_column', $items + ['spec' => ['name' => 'extra', 'type' => $bad]], 'Give the column a type');
        }

        $preview = $c->ok('save_column', $items + ['run' => false, 'spec' => [
            'name' => 'extra', 'type' => 'text', 'default' => ['mode' => 'text', 'value' => "it's"], 'comment' => "a 'quoted' note",
        ]]);
        check(count($preview['sql']) >= 1, 'the preview shows the SQL');
        check(str_contains(implode("\n", $preview['sql']), $driver === 'pgsql' ? "'it''s'" : "'it\\'s'"), 'the text default is quoted: '.implode(' | ', $preview['sql']));
        $has = $driver === 'pgsql'
            ? "select count(*) from information_schema.columns where table_name = 'items' and column_name = 'extra'"
            : "select count(*) from information_schema.columns where table_schema = database() and table_name = 'items' and column_name = 'extra'";
        same(0, (int) $pdo->query($has)->fetchColumn(), 'a preview must not add the column');
    });

    // The SQL tab

    test("{$tag} the SQL tab is read only unless changes are allowed", function () use ($c, $db, $count) {
        $before = $count();
        $c->refused('sql', ['db' => $db, 'sql' => 'delete from items']);
        $c->refused('sql', ['db' => $db, 'sql' => 'commit; delete from items']);
        $c->refused('sql', ['db' => $db, 'sql' => 'select 1; delete from items']);
        same($before, $count());
    });

    test("{$tag} the SQL tab keeps a change only when asked to", function () use ($c, $db, $cell) {
        $c->ok('sql', ['db' => $db, 'sql' => 'update items set note = \'kept\' where id = 1', 'write' => true]);
        same('kept', $cell('note', 1));
    });

    test("{$tag} the SQL tab keeps nothing when a script with changes fails", function () use ($c, $db, $cell) {
        $message = $c->refused('sql', ['db' => $db, 'sql' => "update items set note = 'lost' where id = 3; select * from no_such_table", 'write' => true]);
        check(! str_contains($message, 'may have been kept'), "nothing was kept, and the message says otherwise: {$message}");
        same(null, $cell('note', 3));
    });

    // COMMIT or ROLLBACK in the script itself ends the transaction before the
    // viewer can, so the answer must say the script decided, not the viewer.
    test("{$tag} the SQL tab says when the script ended the transaction itself", function () use ($c, $db, $cell) {
        $r = $c->ok('sql', ['db' => $db, 'sql' => "update items set note = 'undone' where id = 4; rollback", 'write' => true]);
        same(false, $r['committed'], 'the script rolled back, so the viewer did not commit');
        same(true, $r['ended']);
        same(null, $cell('note', 4));

        $r = $c->ok('sql', ['db' => $db, 'sql' => "update items set note = 'own' where id = 5; commit", 'write' => true]);
        same([false, true], [$r['committed'], $r['ended']], 'the script committed, not the viewer');
        same('own', $cell('note', 5));

        $c->refused('sql', ['db' => $db, 'sql' => "update items set note = 'early' where id = 2; commit; select * from no_such_table", 'write' => true],
            'part of the script may have been kept');
        same('early', $cell('note', 2), 'the part before the COMMIT is kept, as the message says');
    });

    if ($driver === 'pgsql') {
        // A deferred key is only checked at COMMIT, so the viewer's own COMMIT
        // fails. PostgreSQL has then undone everything, and the message must not
        // blame the script.
        test("{$tag} the SQL tab keeps nothing when its own COMMIT is refused", function () use ($c, $db, $pdo) {
            $message = $c->refused('sql', ['db' => $db, 'sql' => 'create table deferred_probe (item_id integer references items (id) deferrable initially deferred);'
                .' insert into deferred_probe values (999999)', 'write' => true]);
            check(! str_contains($message, 'may have been kept'), "nothing was kept, and the message says otherwise: {$message}");
            same(0, (int) $pdo->query("select count(*) from information_schema.tables where table_name = 'deferred_probe'")->fetchColumn(), 'the new table was undone too');
        });
    }

    if ($driver === 'mysql') {
        // MySQL commits what came before a CREATE TABLE, even one that then fails.
        // The failed one is the hard case: its error leaves PDO sure that the
        // transaction is still open.
        test("{$tag} the SQL tab says when CREATE TABLE committed the script", function () use ($c, $db, $cell, $pdo) {
            $r = $c->ok('sql', ['db' => $db, 'sql' => "update items set note = 'ddl' where id = 3; create table ddl_probe (id int)", 'write' => true]);
            $pdo->exec('drop table if exists ddl_probe');
            same([false, true], [$r['committed'], $r['ended']]);
            same('ddl', $cell('note', 3));

            $c->refused('sql', ['db' => $db, 'sql' => "update items set note = 'ddl failed' where id = 4; create table ddl_probe like no_such_table", 'write' => true],
                'part of the script may have been kept');
            same('ddl failed', $cell('note', 4), 'CREATE TABLE committed the update before it failed');
        });
    }

    test("{$tag} the SQL tab shows rows, up to the limit", function () use ($c, $db) {
        $r = $c->ok('sql', ['db' => $db, 'sql' => 'select name from items where id <= 3 order by id']);
        same([['apple'], ['banana'], ['cherry']], $r['rows']);
        same(false, $r['committed']);
    });
}

/** The requests that must be refused before any database is touched. */
function http_tests(TestServer $server, string $username, string $password): void
{
    test('api.php answers only POST with the page\'s own header', function () use ($server, $username, $password) {
        $c = new TestClient($server);
        $c->signIn($username, $password);
        same(400, $c->request('GET', '/api.php')['status']);
        same(400, $c->api('databases', [], ['X-Sqlaris' => ''])['status']);
        same(400, $c->request('POST', '/api.php', 'not json', ['X-Sqlaris' => '1'])['status']);
        same(200, $c->api('databases')['status']);
    });

    test('api.php refuses a browser that has not signed in', function () use ($server) {
        $c = new TestClient($server);
        same(401, $c->api('databases')['status']);
    });

    test('a Host header that is not this computer is refused, signed in or not', function () use ($server, $username, $password) {
        $c = new TestClient($server);
        $c->signIn($username, $password);
        same(403, $c->api('databases', [], ['Host' => 'evil.example'])['status']);
        same(403, $c->request('GET', '/', '', ['Host' => 'evil.example'])['status']);
    });

    test('a wrong password or a missing form token does not sign in', function () use ($server, $username, $password) {
        $c = new TestClient($server);
        check(str_contains($c->signIn($username, $password.'x')['body'], 'do not match'), 'wrong password');
        same(401, $c->api('databases')['status']);

        $c = new TestClient($server);
        $c->request('GET', '/');
        $page = $c->request('POST', '/', http_build_query(['username' => $username, 'password' => $password]), ['Content-Type' => 'application/x-www-form-urlencoded']);
        check(str_contains($page['body'], 'form expired'), 'no token');
        same(401, $c->api('databases')['status']);
    });

    test('the router serves the page, the API and assets, and nothing else', function () use ($server) {
        $c = new TestClient($server);

        foreach (['/.env', '/config.php', '/layout.json', '/diagram-views.json', '/src/lib.php', '/assets/../config.php', '/tests/php/run.php'] as $path) {
            same(404, $c->request('GET', $path)['status'], $path);
        }

        same(200, $c->request('GET', '/assets/app.js')['status']);
    });
}
