<?php

declare(strict_types=1);

// api.php over HTTP, against a real database. The requests are the ones the
// page makes, and then the ones a hostile page or a typo would make. Each
// check of what happened reads the database straight through PDO, not through
// the viewer, so the viewer cannot vouch for itself.

/** The tables every run starts with, on each system. */
const FIXTURES = [
    'pgsql' => [
        "create type mood as enum ('happy', 'sad')",
        'create table items (
            id integer generated by default as identity primary key,
            name text not null,
            note text,
            qty integer not null default 0 check (qty >= 0),
            mood mood,
            double_qty integer generated always as (qty * 2) stored
        )',
        'create table "odd ""name"" table" (id integer primary key, "odd ""col""" text)',
        'create table no_pk (a integer)',
        'create table scratch (id integer primary key)',
        "insert into items (name, qty) values ('apple', 1), ('banana', 2), ('cherry', 3), ('50% off', 4), ('under_score', 5)",
        'create index items_name_idx on items (name)',
        'create table item_tags (id integer primary key, item_id integer not null references items (id) on delete cascade, tag text)',
        "insert into item_tags values (1, 1, 'fruit'), (2, 1, 'red')",
        'create view cheap_items as select id, name from items where qty < 3',
        'insert into "odd ""name"" table" values (1, \'x\')',
        'insert into no_pk values (1)',
        'insert into scratch values (1), (2)',
    ],
    'mysql' => [
        "create table items (
            id int auto_increment primary key,
            name varchar(200) not null,
            note text,
            qty int not null default 0 check (qty >= 0),
            mood enum('happy', 'sad'),
            double_qty int as (qty * 2) stored
        )",
        'create table `odd ``name`` table` (id int primary key, `odd ``col``` text)',
        'create table no_pk (a int)',
        'create table scratch (id int primary key)',
        "insert into items (name, qty) values ('apple', 1), ('banana', 2), ('cherry', 3), ('50% off', 4), ('under_score', 5)",
        'create index items_name_idx on items (name)',
        'create table item_tags (id int primary key, item_id int not null, tag varchar(50), foreign key (item_id) references items (id) on delete cascade)',
        "insert into item_tags values (1, 1, 'fruit'), (2, 1, 'red')",
        'create view cheap_items as select id, name from items where qty < 3',
        "insert into `odd ``name`` table` values (1, 'x')",
        'insert into no_pk values (1)',
        'insert into scratch values (1), (2)',
    ],
];

/**
 * The tests for one server. $pdo is a connection of the tests' own to the
 * test database, $db the id the page uses for it. $connect opens another
 * connection of the tests' own, to any database on the server, and $signIn
 * gives a second browser that is signed in.
 *
 * @param  callable(string): PDO  $connect
 * @param  callable(): TestClient  $signIn
 */
function api_tests(string $tag, string $driver, TestClient $c, string $db, PDO $pdo, callable $connect, callable $signIn): void
{
    $q = $driver === 'pgsql' ? fn ($n) => '"'.str_replace('"', '""', $n).'"' : fn ($n) => '`'.str_replace('`', '``', $n).'`';
    $count = fn (string $table = 'items') => (int) $pdo->query('select count(*) from '.$q($table))->fetchColumn();
    $cell = fn (string $column, int $id, string $table = 'items') => $pdo->query('select '.$q($column).' from '.$q($table).' where id = '.$id)->fetchColumn();
    $items = ['db' => $db, 'table' => ['name' => 'items']];
    $rows = fn (array $extra = []) => $c->ok('rows', $items + $extra);
    $names = function (array $answer): array {
        $at = array_search('name', array_column($answer['table']['columns'], 'name'), true);

        return array_map(fn ($row) => $row[$at], $answer['rows']);
    };

    // What the database says about itself, for the tests that make and drop things of their own.
    $schema = $driver === 'pgsql' ? "'public'" : 'database()';
    $tablesOf = fn (PDO $on, bool $baseOnly = false): array => $on->query("select table_name as name from information_schema.tables where table_schema = {$schema}"
        .($baseOnly ? " and table_type = 'BASE TABLE'" : '').' order by table_name')->fetchAll(PDO::FETCH_COLUMN);
    $hasTable = fn (string $name): bool => in_array($name, $tablesOf($pdo), true);
    $columnsOf = function (string $table) use ($pdo, $schema): array {
        $read = $pdo->prepare("select column_name as name from information_schema.columns where table_schema = {$schema} and table_name = ? order by ordinal_position");
        $read->execute([$table]);

        return $read->fetchAll(PDO::FETCH_COLUMN);
    };
    $columnInfo = function (string $table, string $name) use ($pdo, $schema): ?array {
        $read = $pdo->prepare("select is_nullable as nullable, data_type as type, character_maximum_length as len from information_schema.columns
            where table_schema = {$schema} and table_name = ? and column_name = ?");
        $read->execute([$table, $name]);

        return $read->fetch(PDO::FETCH_ASSOC) ?: null;
    };
    $commentOf = function (string $table, string $column) use ($pdo, $driver): ?string {
        $read = $driver === 'pgsql'
            ? $pdo->prepare('select col_description(a.attrelid, a.attnum) from pg_attribute a where a.attrelid = ?::regclass and a.attname = ?')
            : $pdo->prepare('select column_comment from information_schema.columns where table_schema = database() and table_name = ? and column_name = ?');
        $read->execute([$driver === 'pgsql' ? 'public.'.$table : $table, $column]);
        $comment = $read->fetchColumn();

        return $comment === false || $comment === '' ? null : $comment;
    };
    $indexesOf = function (PDO $on, string $table) use ($driver): array {
        $read = $on->prepare($driver === 'pgsql'
            ? "select indexname as name from pg_indexes where schemaname = 'public' and tablename = ?"
            : 'select distinct index_name as name from information_schema.statistics where table_schema = database() and table_name = ?');
        $read->execute([$table]);

        return $read->fetchAll(PDO::FETCH_COLUMN);
    };
    $dropTables = function (string ...$names) use ($pdo, $q): void {
        foreach ($names as $name) {
            $pdo->exec('drop table if exists '.$q($name));
        }
    };
    // Whether the server has a database of that name. It asks over a connection of its own, so it still works
    // after a test has ended $pdo.
    $hasDatabase = function (string $name) use ($connect, $driver): bool {
        $ask = $connect(TEST_DATABASE)->prepare($driver === 'pgsql'
            ? 'select count(*) from pg_database where datname = ?'
            : 'select count(*) from information_schema.schemata where schema_name = ?');
        $ask->execute([$name]);

        return (int) $ask->fetchColumn() > 0;
    };
    // How many sessions the server has under this id.
    $sessions = fn (int $id): int => (int) $pdo->query($driver === 'pgsql'
        ? "select count(*) from pg_stat_activity where pid = {$id}"
        : "select count(*) from information_schema.processlist where id = {$id}")->fetchColumn();
    $sessionId = fn (PDO $on): int => (int) $on->query($driver === 'pgsql' ? 'select pg_backend_pid()' : 'select connection_id()')->fetchColumn();
    // Rows of the tests' own in items, put in through $pdo and taken out again by name, so the fixtures stay as they are.
    $addItems = function (string ...$names) use ($pdo): array {
        $ids = [];

        foreach ($names as $name) {
            $pdo->prepare('insert into items (name) values (?)')->execute([$name]);
            $find = $pdo->prepare('select id from items where name = ?');
            $find->execute([$name]);
            $ids[$name] = (int) $find->fetchColumn();
        }

        return $ids;
    };
    $removeItems = function (array $names) use ($pdo): void {
        $delete = $pdo->prepare('delete from items where name = ?');

        foreach ($names as $name) {
            $delete->execute([$name]);
        }
    };
    $present = fn (array $ids): array => array_map('intval', $pdo->query('select id from items where id in ('.implode(', ', array_map('intval', $ids)).') order by id')->fetchAll(PDO::FETCH_COLUMN));

    // Reading

    test("{$tag} rows come back with their count", function () use ($rows) {
        $r = $rows();
        same(5, $r['total']);
        same(5, count($r['rows']));
    });

    test("{$tag} every screen's data loads", function () use ($c, $db, $items) {
        $tags = ['db' => $db, 'table' => ['name' => 'item_tags']];

        $tables = $c->ok('tables', ['db' => $db]);
        $names = array_column($tables['tables'], 'name');
        check(in_array('items', $names, true) && in_array('cheap_items', $names, true), 'tables: '.implode(', ', $names));
        check($tables['info']['maintenance'] !== [], 'the upkeep this system offers');

        $structure = $c->ok('structure', $items);
        same(['id', 'name', 'note', 'qty', 'mood', 'double_qty'], array_column($structure['table']['columns'], 'name'));
        same(true, $structure['table']['columns'][5]['readonly'], 'double_qty is filled by the database');
        same(['happy', 'sad'], $structure['table']['columns'][4]['options'] ?? ['happy', 'sad'], 'the enum values');
        check(count($structure['indexes']) >= 2, 'the primary key and items_name_idx');
        same('item_tags', $structure['table']['refs'][0]['tbl'] ?? null, 'item_tags points here');

        $fk = $c->ok('structure', $tags);
        same('items', $fk['table']['fks'][0]['tbl'] ?? null, 'item_tags points at items');
        check($c->ok('structure', ['db' => $db, 'table' => ['name' => 'cheap_items']])['view'] !== null, 'a view shows its query');

        same(2, $c->ok('refs', $items + ['row' => ['id' => '1']])['refs'][0]['count']);
        same(5, (int) $c->ok('values', $items + ['col' => 'qty'])['stats']['total']);
        check($c->ok('lookup', $items + ['col' => 'id', 'q' => 'app'])['items'] !== [], 'a foreign key search finds apple');
        check(count($c->ok('schema', ['db' => $db])['tables']) >= 5, 'the SQL editor gets the tables');
        check(count($c->ok('diagram', ['db' => $db])['tables']) >= 5, 'the diagram gets the tables');
        check(isset($c->ok('health', ['db' => $db])['findings']), 'health');
        check(isset($c->ok('activity', ['db' => $db])['sessions']), 'activity');

        $op = $tables['info']['maintenance'][1]['op'];
        check(isset($c->ok('maintain', $items + ['op' => $op])['after']), "maintain {$op}");
        $c->refused('maintain', $items + ['op' => 'drop'], 'no such upkeep');
    });

    // Views are kept in a file of the viewer's own, so the checks read that file.
    test("{$tag} a diagram view is saved, comes back with the diagram, and is deleted", function () use ($c, $db) {
        $onDisk = fn () => json_decode((string) file_get_contents($c->server->views), true);
        $saved = $c->ok('save_view', ['db' => $db, 'view' => [
            'name' => '  Items  ',
            'tables' => ['s.items', 's.item_tags', 's.items', 42],
            'at' => ['s.items' => [10.4, -20], 's.item_tags' => ['x', 1], 's.gone' => [1, 2]],
            'layout' => 'flow',
            'detail' => 'names',
        ]])['views'];
        same(['Items'], array_column($saved, 'name'));
        $view = $onDisk()[$db][0];
        same(['s.items', 's.item_tags'], $view['tables']);
        same(['s.items' => [10, -20]], $view['at'], 'a place that is not two numbers, or of a table not in the view, is dropped');
        same(['flow', 'names'], [$view['layout'], $view['detail']]);
        same($saved, $c->ok('diagram', ['db' => $db])['views']);

        $c->ok('save_view', ['db' => $db, 'view' => ['name' => 'items', 'tables' => ['s.items'], 'layout' => 'drop', 'detail' => 'x']]);
        $views = $onDisk()[$db];
        same(1, count($views), 'the same name in another case replaces the view');
        same(['s.items'], $views[0]['tables']);
        same(['flow', 'keys'], [$views[0]['layout'], $views[0]['detail']], 'a layout or detail not on the list falls back');

        same([], $c->ok('delete_view', ['db' => $db, 'name' => 'ITEMS'])['views']);
        check(! isset($onDisk()[$db]), 'nothing is kept for the database');
    });

    test("{$tag} a view needs a name and a table, and its text is only ever text", function () use ($c, $db, $count) {
        $c->refused('save_view', ['db' => $db, 'view' => ['name' => '   ', 'tables' => ['s.items']]], 'Give the view a name');
        $c->refused('save_view', ['db' => $db, 'view' => 'not a view'], 'Give the view a name');
        $c->refused('save_view', ['db' => $db, 'view' => ['name' => 'Empty', 'tables' => []]], 'at least one table');
        $c->refused('save_view', ['db' => $db, 'view' => ['name' => str_repeat('x', 61), 'tables' => ['s.items']]], 'up to 60 characters');
        $c->refused('save_view', ['db' => 'nowhere/x', 'view' => ['name' => 'X', 'tables' => ['s.items']]], 'not on the list');
        $c->refused('delete_view', ['db' => 'nowhere/x', 'name' => 'X'], 'not on the list');

        $sql = "x'); drop table items; --";
        same([$sql], $c->ok('save_view', ['db' => $db, 'view' => ['name' => $sql, 'tables' => [$sql]]])['views'][0]['tables']);
        same(5, $count(), 'nothing in a view reaches the database');
        same([], $c->ok('delete_view', ['db' => $db, 'name' => $sql])['views']);
    });

    test("{$tag} a views file that does not read is never written over", function () use ($c, $db) {
        $broken = "{\"other/db\": [{\"name\": \"Kept\", \"tables\": [\"s.a\"]},]}\n";
        file_put_contents($c->server->views, $broken);
        $c->refused('save_view', ['db' => $db, 'view' => ['name' => 'New', 'tables' => ['s.items']]], 'Could not read diagram-views.json');
        $c->refused('delete_view', ['db' => $db, 'name' => 'Kept'], 'Could not read diagram-views.json');
        same($broken, file_get_contents($c->server->views), 'the file is as it was');
        unlink($c->server->views);
    });

    test("{$tag} an export gives every matching row, in each format", function () use ($c, $items) {
        foreach (['csv' => 'apple', 'json' => '"name":"apple"', 'sql' => "'apple'"] as $format => $expect) {
            $r = $c->api('export', $items + ['format' => $format, 'filters' => [['col' => 'name', 'op' => 'eq', 'value' => 'apple']]]);
            same(200, $r['status'], $format);
            check(str_contains($r['body'], $expect), "{$format} has apple: ".substr($r['body'], 0, 200));
            check(! str_contains($r['body'], 'banana'), "{$format} keeps to the filter");
        }
    });

    test("{$tag} a table name with SQL in it is looked up, not run", function () use ($c, $db, $count) {
        foreach (['items; drop table items; --', 'items" where 1=1 --', 'items` --', "items'"] as $name) {
            $c->refused('rows', ['db' => $db, 'table' => ['name' => $name]], 'There is no table');
        }

        $c->refused('rows', ['db' => $db, 'table' => ['schema' => 'x; drop table items', 'name' => 'items']], 'There is no table');
        same(5, $count());
    });

    test("{$tag} a table whose real name has the quote character in it works", function () use ($c, $db, $pdo, $q, $driver) {
        // The character each system quotes names with, inside the name itself.
        $mark = $driver === 'pgsql' ? '"' : '`';
        $table = "odd {$mark}name{$mark} table";
        $column = "odd {$mark}col{$mark}";
        $odd = ['db' => $db, 'table' => ['name' => $table]];
        same(1, $c->ok('rows', $odd)['total']);
        $c->ok('update', $odd + ['keys' => [['id' => '1']], 'changes' => [$column => 'y']]);
        same('y', $pdo->query('select '.$q($column).' from '.$q($table))->fetchColumn());
    });

    test("{$tag} a filter or sort on a column that is not there is refused", function () use ($c, $items) {
        $c->refused('rows', $items + ['filters' => [['col' => 'name; drop table items', 'op' => 'eq', 'value' => 'x']]], 'has no column');
        $c->refused('rows', $items + ['sort' => ['col' => 'id desc; drop table items', 'dir' => 'asc']], 'has no column');
    });

    test("{$tag} a filter operator must be one of the known ones", function () use ($c, $items) {
        $c->refused('rows', $items + ['filters' => [['col' => 'name', 'op' => '= 1 or 1=1 --', 'value' => 'x']]], 'Unknown filter');
    });

    test("{$tag} a sort direction other than desc sorts ascending", function () use ($rows, $names) {
        $asc = $names($rows(['sort' => ['col' => 'name', 'dir' => 'asc']]));
        same($asc, $names($rows(['sort' => ['col' => 'name', 'dir' => 'desc; drop table items']])));
        same(array_reverse($asc), $names($rows(['sort' => ['col' => 'name', 'dir' => 'desc']])));
    });

    test("{$tag} a filter value is bound, so quotes in it match nothing extra", function () use ($rows) {
        same(0, $rows(['filters' => [['col' => 'name', 'op' => 'eq', 'value' => "x' or '1'='1"]]])['total']);
        same(0, $rows(['filters' => [['col' => 'name', 'op' => 'contains', 'value' => "' or 1=1 --"]]])['total']);
        same(1, $rows(['filters' => [['col' => 'name', 'op' => 'in', 'value' => "apple, x') or ('1'='1"]]])['total']);
        same(0, $rows(['filters' => [['col' => 'qty', 'op' => 'gt', 'value' => '100']]])['total']);
    });

    test("{$tag} a search for % or _ finds those characters, not everything", function () use ($rows, $names) {
        same(['50% off'], $names($rows(['search' => '50%'])));
        same(['under_score'], $names($rows(['search' => '_'])));
        same(0, $rows(['search' => "'; drop table items; --"])['total']);
    });

    test("{$tag} paging is clamped, and a page size cannot carry SQL", function () use ($rows) {
        same(1000, $rows(['perPage' => 999999])['perPage']);
        same(1, $rows(['perPage' => '1; drop table items'])['perPage']);
        same(1, $rows(['page' => -5])['page']);
    });

    test("{$tag} a database that is not on the list cannot be opened", function () use ($c, $driver) {
        $c->refused('tables', ['db' => ($driver === 'pgsql' ? 'pg' : 'my').'/'.($driver === 'pgsql' ? 'postgres' : 'mysql')], 'not on the list');
        $c->refused('tables', ['db' => 'nope/items'], 'not on the list');
    });

    // Writing

    test("{$tag} a value with SQL in it is stored exactly as typed", function () use ($c, $items, $count, $pdo) {
        $before = $count();
        $name = "Robert'); drop table items; --";
        $note = "\" ` \\ ' ; -- /* */ \\x00";
        $c->ok('insert', $items + ['values' => ['name' => $name, 'note' => $note, 'qty' => '7']]);
        same($before + 1, $count());
        $row = $pdo->query('select name, note from items where qty = 7')->fetch(PDO::FETCH_ASSOC);
        same(['name' => $name, 'note' => $note], $row);
    });

    test("{$tag} an update changes one row and no other", function () use ($c, $items, $cell) {
        $c->ok('update', $items + ['keys' => [['id' => '2']], 'changes' => ['qty' => '20']]);
        same('20', (string) $cell('qty', 2));
        same('1', (string) $cell('qty', 1));
        same('3', (string) $cell('qty', 3));
    });

    test("{$tag} a row key with SQL in it is refused, and no row changes", function () use ($c, $items, $pdo) {
        $before = $pdo->query('select id, qty from items order by id')->fetchAll(PDO::FETCH_KEY_PAIR);
        // PostgreSQL refuses these as integers. MySQL would read most of them as 1,
        // and a DELETE would then remove row 1, so the viewer refuses them first.
        foreach (['1 or 1=1', '1abc', '1; drop table items', '', '1.0e0x'] as $key) {
            $c->refused('update', $items + ['keys' => [['id' => $key]], 'changes' => ['qty' => '99']]);
            $c->refused('delete', $items + ['keys' => [['id' => $key]]]);
        }

        same($before, $pdo->query('select id, qty from items order by id')->fetchAll(PDO::FETCH_KEY_PAIR));
    });

    test("{$tag} a change to a column that is not there, or that the database fills, is refused", function () use ($c, $items, $cell) {
        $c->refused('update', $items + ['keys' => [['id' => '1']], 'changes' => ['qty = 0, name' => 'x']], 'has no column');
        $c->refused('update', $items + ['keys' => [['id' => '1']], 'changes' => ['double_qty' => '9']], 'filled by the database');
        same('1', (string) $cell('qty', 1));
    });

    test("{$tag} an update needs the row key, and a row that is gone saves nothing", function () use ($c, $items) {
        $c->refused('update', $items + ['keys' => [[]], 'changes' => ['qty' => '0']], 'row key is missing');
        $c->refused('update', $items + ['keys' => [['id' => '999999']], 'changes' => ['qty' => '0']], 'not there any more');
        $c->refused('update', $items + ['keys' => [], 'changes' => ['qty' => '0']], 'at least one row');
        $c->refused('delete', $items + ['keys' => array_fill(0, 1001, ['id' => '1'])], 'At most 1000');
    });

    test("{$tag} a table without a primary key cannot be edited row by row", function () use ($c, $db, $count) {
        $c->refused('update', ['db' => $db, 'table' => ['name' => 'no_pk'], 'keys' => [['a' => '1']], 'changes' => ['a' => '2']], 'no primary key');
        $c->refused('delete', ['db' => $db, 'table' => ['name' => 'no_pk'], 'keys' => [['a' => '1']]], 'no primary key');
        same(1, $count('no_pk'));
    });

    test("{$tag} a paste over many rows is kept whole or not at all", function () use ($c, $items, $cell) {
        $c->refused('update_each', $items + ['items' => [
            ['key' => ['id' => '1'], 'changes' => ['qty' => '10']],
            ['key' => ['id' => '3'], 'changes' => ['qty' => '-1']],
        ]]);
        same('1', (string) $cell('qty', 1), 'the first row must be rolled back');
    });

    test("{$tag} an import with one bad row keeps none, and names the row", function () use ($c, $items, $count) {
        $before = $count();
        $c->refused('import', $items + ['columns' => ['name', 'qty'], 'rows' => [['kiwi', '1'], ['bad', '-5'], ['lime', '2']]], 'Row 2');
        $c->refused('import', $items + ['columns' => ['name', 'qty'], 'rows' => [['kiwi', '1'], ['lime', 'two']]], 'Row 2');
        same($before, $count());
        $c->refused('import', $items + ['columns' => ['double_qty'], 'rows' => [['1']]], 'filled by the database');
        $c->refused('import', $items + ['columns' => ['name; drop table items'], 'rows' => [['x']]], 'has no column');
        $c->ok('import', $items + ['columns' => ['name', 'qty'], 'rows' => [['kiwi', '1'], ['lime', '2']]]);
        same($before + 2, $count());
    });

    // The next tests work on rows of their own, put in through $pdo and taken out again, because the tests
    // after them read the fixture rows by their ids.

    test("{$tag} a delete removes the rows whose keys are sent, and the rows that point at them", function () use ($c, $items, $pdo, $count, $addItems, $removeItems, $present) {
        $names = ['probe gone one', 'probe gone two', 'probe kept one', 'probe kept two'];
        $ids = $addItems(...$names);

        try {
            // Tags 9001 to 9005: two on the first row to go, one on the second, one on each row that stays.
            $addTag = $pdo->prepare('insert into item_tags (id, item_id, tag) values (?, ?, ?)');

            foreach ([[9001, 'probe gone one'], [9002, 'probe gone one'], [9003, 'probe gone two'], [9004, 'probe kept one'], [9005, 'probe kept two']] as [$tagId, $owner]) {
                $addTag->execute([$tagId, $ids[$owner], 'probe']);
            }

            $itemsBefore = $count();
            $tagsBefore = $count('item_tags');

            $r = $c->ok('delete', $items + ['keys' => [['id' => (string) $ids['probe gone one']], ['id' => (string) $ids['probe gone two']]]]);

            same(2, $r['deleted']);
            same([$ids['probe kept one'], $ids['probe kept two']], $present($ids), 'only the two rows that were sent are gone');
            same([9004, 9005], array_map('intval', $pdo->query('select id from item_tags where id between 9001 and 9005 order by id')->fetchAll(PDO::FETCH_COLUMN)),
                'the tags of the deleted rows went with them, and the others stayed');
            same($itemsBefore - 2, $count());
            same($tagsBefore - 3, $count('item_tags'));
            same(2, (int) $pdo->query('select count(*) from item_tags where item_id = 1')->fetchColumn(), 'the tags of a row that was not sent are as they were');
        } finally {
            $removeItems($names);
        }
    });

    test("{$tag} a delete that names a row that is gone deletes none of the rows", function () use ($c, $items, $count, $addItems, $removeItems, $present) {
        $names = ['probe stays one', 'probe stays two'];
        $ids = $addItems(...$names);

        try {
            $before = $count();
            // The good row comes first, so a delete that had already run it would show.
            $c->refused('delete', $items + ['keys' => [['id' => (string) $ids['probe stays one']], ['id' => '999999'], ['id' => (string) $ids['probe stays two']]]], 'not there any more');

            same($before, $count());
            same(array_values($ids), $present($ids));
        } finally {
            $removeItems($names);
        }
    });

    test("{$tag} a paste over several rows changes each of them and nothing else", function () use ($c, $items, $pdo, $addItems, $removeItems) {
        $names = ['probe each one', 'probe each two', 'probe each three', 'probe bystander'];
        $ids = $addItems(...$names);
        $snapshot = fn (): array => array_column($pdo->query('select id, name, note, qty from items order by id')->fetchAll(PDO::FETCH_ASSOC), null, 'id');
        $key = fn (string $name): array => ['id' => (string) $ids[$name]];
        $shown = fn (array $row): array => [$row['name'], $row['note'], (string) $row['qty']];

        try {
            $before = $snapshot();

            $r = $c->ok('update_each', $items + ['items' => [
                ['key' => $key('probe each one'), 'changes' => ['qty' => '11']],
                ['key' => $key('probe each two'), 'changes' => ['note' => 'second', 'qty' => '12']],
                ['key' => $key('probe each three'), 'changes' => ['name' => 'probe each 3']],
            ]]);
            $after = $snapshot();

            same(3, count($r['rows']), 'the answer has the three rows');
            same(['probe each one', null, '11'], $shown($after[$ids['probe each one']]));
            same(['probe each two', 'second', '12'], $shown($after[$ids['probe each two']]));
            same(['probe each 3', null, '0'], $shown($after[$ids['probe each three']]));
            same(array_keys($before), array_keys($after), 'no row was added or removed');

            foreach ($before as $id => $row) {
                if (! in_array($id, [$ids['probe each one'], $ids['probe each two'], $ids['probe each three']], true)) {
                    same($row, $after[$id], "row {$id} was not part of the paste, so it stays as it was");
                }
            }

            $c->refused('update_each', $items + ['items' => []], 'between 1 and 1000');
        } finally {
            $removeItems([...$names, 'probe each 3']);
        }
    });

    test("{$tag} emptying or dropping needs the exact name typed back", function () use ($c, $db, $count) {
        $scratch = ['db' => $db, 'table' => ['name' => 'scratch']];
        $c->refused('truncate', $scratch + ['confirm' => 'Scratch'], 'Type the table name');
        $c->refused('drop_table', $scratch + ['confirm' => ''], 'Type the table name');
        $c->refused('drop_column', $scratch + ['column' => 'id', 'confirm' => 'nope'], 'Type the column name');
        same(2, $count('scratch'));
        $c->ok('truncate', $scratch + ['confirm' => 'scratch']);
        same(0, $count('scratch'));
    });

    test("{$tag} new table and database names are refused unless plain", function () use ($c, $db) {
        $scratch = ['db' => $db, 'table' => ['name' => 'scratch']];

        foreach (['x; drop table items', 'a b', 'x"', 'x`', ''] as $bad) {
            $c->refused('rename_table', $scratch + ['to' => $bad], 'letters, digits and underscores');
            $c->refused('copy_table', $scratch + ['to' => $bad], 'letters, digits and underscores');
            $c->refused('create_database', ['db' => $db, 'name' => $bad], 'letters, digits and underscores');
        }
    });

    test("{$tag} a column type cannot end the statement, and a preview changes nothing", function () use ($c, $items, $pdo, $driver) {
        foreach (['text; drop table items', 'text -- x', 'text /* x */'] as $bad) {
            $c->refused('save_column', $items + ['spec' => ['name' => 'extra', 'type' => $bad]], 'Give the column a type');
        }

        $preview = $c->ok('save_column', $items + ['run' => false, 'spec' => [
            'name' => 'extra', 'type' => 'text', 'default' => ['mode' => 'text', 'value' => "it's"], 'comment' => "a 'quoted' note",
        ]]);
        check(count($preview['sql']) >= 1, 'the preview shows the SQL');
        check(str_contains(implode("\n", $preview['sql']), $driver === 'pgsql' ? "'it''s'" : "'it\\'s'"), 'the text default is quoted: '.implode(' | ', $preview['sql']));
        $has = $driver === 'pgsql'
            ? "select count(*) from information_schema.columns where table_name = 'items' and column_name = 'extra'"
            : "select count(*) from information_schema.columns where table_schema = database() and table_name = 'items' and column_name = 'extra'";
        same(0, (int) $pdo->query($has)->fetchColumn(), 'a preview must not add the column');
    });

    // Tables and columns. Each test makes the tables it needs through $pdo and drops what it leaves.

    test("{$tag} renaming a table moves its rows to the new name", function () use ($c, $db, $pdo, $count, $hasTable, $dropTables) {
        $dropTables('probe_before', 'probe_after');
        $pdo->exec('create table probe_before (id integer primary key, label varchar(50))');
        $pdo->exec("insert into probe_before values (1, 'one'), (2, 'two'), (3, 'three')");

        try {
            $r = $c->ok('rename_table', ['db' => $db, 'table' => ['name' => 'probe_before'], 'to' => 'probe_after']);

            same('probe_after', $r['name']);
            same([false, true], [$hasTable('probe_before'), $hasTable('probe_after')], 'the old name is gone and the new one is there');
            same([1 => 'one', 2 => 'two', 3 => 'three'], $pdo->query('select id, label from probe_after order by id')->fetchAll(PDO::FETCH_KEY_PAIR));

            // A name that is taken is refused, and the table is where it was, with its rows.
            $before = $count();
            $c->refused('rename_table', ['db' => $db, 'table' => ['name' => 'probe_after'], 'to' => 'items'], 'already exists');
            same(true, $hasTable('probe_after'));
            same(3, $count('probe_after'));
            same($before, $count());
        } finally {
            $dropTables('probe_before', 'probe_after');
        }
    });

    test("{$tag} a table or view is dropped only when its name is typed back exactly", function () use ($c, $db, $pdo, $hasTable, $dropTables) {
        $dropTables('probe_drop');
        $pdo->exec('create table probe_drop (id integer primary key)');
        $pdo->exec('insert into probe_drop values (1)');
        $pdo->exec('create view probe_drop_view as select id from probe_drop');
        $table = ['db' => $db, 'table' => ['name' => 'probe_drop']];
        $view = ['db' => $db, 'table' => ['name' => 'probe_drop_view']];

        try {
            $c->refused('drop_table', $table + ['confirm' => 'PROBE_DROP'], 'Type the table name');
            $c->refused('drop_table', $view + ['confirm' => 'probe_drop'], 'Type the table name');
            $c->refused('drop_table', $table, 'Type the table name');
            same([true, true], [$hasTable('probe_drop'), $hasTable('probe_drop_view')], 'a wrong name drops nothing');

            $c->ok('drop_table', $view + ['confirm' => 'probe_drop_view']);
            same([true, false], [$hasTable('probe_drop'), $hasTable('probe_drop_view')], 'the view is gone, and the table under it is not');

            $c->ok('drop_table', $table + ['confirm' => 'probe_drop']);
            same(false, $hasTable('probe_drop'));
        } finally {
            $pdo->exec('drop view if exists probe_drop_view');
            $dropTables('probe_drop');
        }
    });

    // The table the copies are made from has what a copy has to bring over: a numbered key, a default, a check
    // and a column the database works out itself. Its ids skip from 1 to 5, so a copy that counted its rows
    // would number the next one wrong.
    $probeSource = [
        'pgsql' => "create table probe_src (id integer generated by default as identity primary key, label varchar(50) not null default 'x',
            qty integer not null default 0 check (qty >= 0), double_qty integer generated always as (qty * 2) stored)",
        'mysql' => "create table probe_src (id int auto_increment primary key, label varchar(50) not null default 'x',
            qty int not null default 0 check (qty >= 0), double_qty int as (qty * 2) stored)",
    ][$driver];

    test("{$tag} a copy of a table has the same columns and rows, and its numbering carries on", function () use ($c, $db, $pdo, $q, $probeSource, $hasTable, $columnsOf, $dropTables) {
        $dropTables('probe_src', 'probe_copy');
        $pdo->exec($probeSource);
        $pdo->exec("insert into probe_src (id, label, qty) values (1, 'one', 1), (5, 'five', 5)");
        $read = fn (string $table): array => $pdo->query('select id, label, qty, double_qty from '.$q($table).' order by id')->fetchAll(PDO::FETCH_NUM);

        try {
            $r = $c->ok('copy_table', ['db' => $db, 'table' => ['name' => 'probe_src'], 'to' => 'probe_copy']);

            same('probe_copy', $r['name']);
            same(true, $hasTable('probe_copy'));
            same($columnsOf('probe_src'), $columnsOf('probe_copy'), 'the same columns, in the same order');
            same(2, count($read('probe_copy')), 'the rows came along');
            same($read('probe_src'), $read('probe_copy'), 'the same rows, the computed column included');
            same(2, count($read('probe_src')), 'the original still has its rows');

            $pdo->exec("insert into probe_copy (label) values ('next')");
            $next = (int) $pdo->query("select id from probe_copy where label = 'next'")->fetchColumn();
            check($next > 5, "a new row in the copy is numbered after the highest key that was copied, and got {$next}");
        } finally {
            $dropTables('probe_src', 'probe_copy');
        }
    });

    test("{$tag} a copy without rows is empty, and keeps the columns, the default and the key", function () use ($c, $db, $pdo, $count, $probeSource, $hasTable, $columnsOf, $dropTables) {
        $dropTables('probe_src', 'probe_empty');
        $pdo->exec($probeSource);
        $pdo->exec("insert into probe_src (id, label, qty) values (1, 'one', 1), (5, 'five', 5)");

        try {
            $c->ok('copy_table', ['db' => $db, 'table' => ['name' => 'probe_src'], 'to' => 'probe_empty', 'rows' => false]);

            same(true, $hasTable('probe_empty'));
            same(0, $count('probe_empty'));
            same($columnsOf('probe_src'), $columnsOf('probe_empty'));
            same(2, $count('probe_src'), 'the original still has its rows');

            $pdo->exec('insert into probe_empty (id) values (7)');
            same('x', $pdo->query('select label from probe_empty where id = 7')->fetchColumn(), 'the default came along');
            fails(fn () => $pdo->exec('insert into probe_empty (id) values (7)'));
            fails(fn () => $pdo->exec('insert into probe_empty (id, qty) values (8, -1)'));
        } finally {
            $dropTables('probe_src', 'probe_empty');
        }
    });

    test("{$tag} a copy onto a name that is taken, or of a view, is refused and makes nothing", function () use ($c, $db, $count, $hasTable) {
        $before = $count();

        $c->refused('copy_table', ['db' => $db, 'table' => ['name' => 'scratch'], 'to' => 'items'], 'already exists');
        same($before, $count());

        $c->refused('copy_table', ['db' => $db, 'table' => ['name' => 'cheap_items'], 'to' => 'probe_from_view'], 'Only a table can be copied');
        same(false, $hasTable('probe_from_view'));
    });

    test("{$tag} saving a new column adds it, with its type, default and comment", function () use ($c, $db, $pdo, $columnsOf, $columnInfo, $commentOf, $dropTables) {
        $dropTables('probe_add_col');
        $pdo->exec('create table probe_add_col (id integer primary key)');
        $pdo->exec('insert into probe_add_col values (1)');

        try {
            $r = $c->ok('save_column', ['db' => $db, 'table' => ['name' => 'probe_add_col'], 'run' => true, 'spec' => [
                'name' => 'label', 'type' => 'varchar(20)', 'nullable' => false,
                'default' => ['mode' => 'text', 'value' => "it's here"], 'comment' => 'a short label',
            ]]);

            check(count($r['sql']) >= 1, 'the answer says what ran');
            same(['id', 'label'], $columnsOf('probe_add_col'));
            $info = $columnInfo('probe_add_col', 'label');
            same(['NO', 20], [$info['nullable'] ?? null, (int) ($info['len'] ?? 0)], 'not null, and the type that was asked for');
            same('a short label', $commentOf('probe_add_col', 'label'));
            same("it's here", $pdo->query('select label from probe_add_col where id = 1')->fetchColumn(), 'the row that was there has the default');

            $pdo->exec('insert into probe_add_col (id) values (2)');
            same("it's here", $pdo->query('select label from probe_add_col where id = 2')->fetchColumn(), 'a new row gets the default, quote and all');
        } finally {
            $dropTables('probe_add_col');
        }
    });

    test("{$tag} saving a changed column changes that one, and its rows keep their values", function () use ($c, $db, $pdo, $columnsOf, $columnInfo, $commentOf, $dropTables) {
        $dropTables('probe_change_col');
        $pdo->exec('create table probe_change_col (id integer primary key, qty integer)');
        $pdo->exec('insert into probe_change_col values (1, 5), (2, 6)');
        $change = fn (array $spec): array => $c->ok('save_column', ['db' => $db, 'table' => ['name' => 'probe_change_col'], 'column' => $spec['from'], 'run' => true, 'spec' => array_diff_key($spec, ['from' => 1])]);
        $values = fn (string $column): array => array_map('intval', $pdo->query("select id, {$column} from probe_change_col order by id")->fetchAll(PDO::FETCH_KEY_PAIR));

        try {
            $r = $change(['from' => 'qty', 'name' => 'qty', 'type' => 'integer', 'nullable' => false, 'default' => ['mode' => 'sql', 'value' => '9'], 'comment' => 'how many']);
            check(count($r['sql']) >= 1, 'the answer says what ran');
            same('NO', $columnInfo('probe_change_col', 'qty')['nullable'] ?? null, 'the column is not null now');
            same('how many', $commentOf('probe_change_col', 'qty'));
            $pdo->exec('insert into probe_change_col (id) values (3)');
            same([1 => 5, 2 => 6, 3 => 9], $values('qty'), 'a new row gets the new default, and the old rows are as they were');
            fails(fn () => $pdo->exec('insert into probe_change_col (id, qty) values (4, null)'));

            $change(['from' => 'qty', 'name' => 'qty', 'type' => 'bigint', 'nullable' => false, 'default' => ['mode' => 'sql', 'value' => '9'], 'comment' => 'how many']);
            same('bigint', $columnInfo('probe_change_col', 'qty')['type'] ?? null, 'the type changed');
            $pdo->exec('insert into probe_change_col (id) values (4)');
            same([1 => 5, 2 => 6, 3 => 9, 4 => 9], $values('qty'), 'the values were converted, and the default is still there');

            $change(['from' => 'qty', 'name' => 'amount', 'type' => 'bigint', 'nullable' => false, 'default' => ['mode' => 'sql', 'value' => '9'], 'comment' => 'how many']);
            same(['id', 'amount'], $columnsOf('probe_change_col'), 'the column has its new name, in the same place');
            same([1 => 5, 2 => 6, 3 => 9, 4 => 9], $values('amount'));
            same('NO', $columnInfo('probe_change_col', 'amount')['nullable'] ?? null, 'a rename keeps the rest of the column as it was');
        } finally {
            $dropTables('probe_change_col');
        }
    });

    test("{$tag} dropping a column needs its name typed back, and removes only that column", function () use ($c, $db, $pdo, $columnsOf, $dropTables) {
        $dropTables('probe_drop_col');
        $pdo->exec('create table probe_drop_col (id integer primary key, keep_me varchar(20), drop_me varchar(20))');
        $pdo->exec("insert into probe_drop_col values (1, 'kept', 'gone')");
        $table = ['db' => $db, 'table' => ['name' => 'probe_drop_col']];

        try {
            $c->refused('drop_column', $table + ['column' => 'drop_me', 'confirm' => 'DROP_ME'], 'Type the column name');
            $c->refused('drop_column', $table + ['column' => 'drop_me'], 'Type the column name');
            $c->refused('drop_column', $table + ['column' => 'no_such_column', 'confirm' => 'no_such_column'], 'has no column');
            same(['id', 'keep_me', 'drop_me'], $columnsOf('probe_drop_col'), 'a wrong name drops nothing');

            $c->ok('drop_column', $table + ['column' => 'drop_me', 'confirm' => 'drop_me']);

            same(['id', 'keep_me'], $columnsOf('probe_drop_col'));
            same('kept', $pdo->query('select keep_me from probe_drop_col where id = 1')->fetchColumn(), 'the other columns keep their values');
        } finally {
            $dropTables('probe_drop_col');
        }
    });

    // The SQL tab

    test("{$tag} the SQL tab is read only unless changes are allowed", function () use ($c, $db, $count) {
        $before = $count();
        $c->refused('sql', ['db' => $db, 'sql' => 'delete from items']);
        $c->refused('sql', ['db' => $db, 'sql' => 'commit; delete from items']);
        $c->refused('sql', ['db' => $db, 'sql' => 'select 1; delete from items']);
        same($before, $count());
    });

    test("{$tag} the SQL tab keeps a change only when asked to", function () use ($c, $db, $cell) {
        $c->ok('sql', ['db' => $db, 'sql' => 'update items set note = \'kept\' where id = 1', 'write' => true]);
        same('kept', $cell('note', 1));
    });

    test("{$tag} the SQL tab keeps nothing when a script with changes fails", function () use ($c, $db, $cell) {
        $message = $c->refused('sql', ['db' => $db, 'sql' => "update items set note = 'lost' where id = 3; select * from no_such_table", 'write' => true]);
        check(! str_contains($message, 'may have been kept'), "nothing was kept, and the message says otherwise: {$message}");
        same(null, $cell('note', 3));
    });

    // COMMIT or ROLLBACK in the script itself ends the transaction before the
    // viewer can, so the answer must say the script decided, not the viewer.
    test("{$tag} the SQL tab says when the script ended the transaction itself", function () use ($c, $db, $cell) {
        $r = $c->ok('sql', ['db' => $db, 'sql' => "update items set note = 'undone' where id = 4; rollback", 'write' => true]);
        same(false, $r['committed'], 'the script rolled back, so the viewer did not commit');
        same(true, $r['ended']);
        same(null, $cell('note', 4));

        $r = $c->ok('sql', ['db' => $db, 'sql' => "update items set note = 'own' where id = 5; commit", 'write' => true]);
        same([false, true], [$r['committed'], $r['ended']], 'the script committed, not the viewer');
        same('own', $cell('note', 5));

        $c->refused('sql', ['db' => $db, 'sql' => "update items set note = 'early' where id = 2; commit; select * from no_such_table", 'write' => true],
            'part of the script may have been kept');
        same('early', $cell('note', 2), 'the part before the COMMIT is kept, as the message says');
    });

    if ($driver === 'pgsql') {
        // A deferred key is only checked at COMMIT, so the viewer's own COMMIT
        // fails. PostgreSQL has then undone everything, and the message must not
        // blame the script.
        test("{$tag} the SQL tab keeps nothing when its own COMMIT is refused", function () use ($c, $db, $pdo) {
            $message = $c->refused('sql', ['db' => $db, 'sql' => 'create table deferred_probe (item_id integer references items (id) deferrable initially deferred);'
                .' insert into deferred_probe values (999999)', 'write' => true]);
            check(! str_contains($message, 'may have been kept'), "nothing was kept, and the message says otherwise: {$message}");
            same(0, (int) $pdo->query("select count(*) from information_schema.tables where table_name = 'deferred_probe'")->fetchColumn(), 'the new table was undone too');
        });
    }

    if ($driver === 'mysql') {
        // MySQL commits what came before a CREATE TABLE, even one that then fails.
        // The failed one is the hard case: its error leaves PDO sure that the
        // transaction is still open.
        test("{$tag} the SQL tab says when CREATE TABLE committed the script", function () use ($c, $db, $cell, $pdo) {
            $r = $c->ok('sql', ['db' => $db, 'sql' => "update items set note = 'ddl' where id = 3; create table ddl_probe (id int)", 'write' => true]);
            $pdo->exec('drop table if exists ddl_probe');
            same([false, true], [$r['committed'], $r['ended']]);
            same('ddl', $cell('note', 3));

            $c->refused('sql', ['db' => $db, 'sql' => "update items set note = 'ddl failed' where id = 4; create table ddl_probe like no_such_table", 'write' => true],
                'part of the script may have been kept');
            same('ddl failed', $cell('note', 4), 'CREATE TABLE committed the update before it failed');
        });
    }

    test("{$tag} the SQL tab shows rows, up to the limit", function () use ($c, $db) {
        $r = $c->ok('sql', ['db' => $db, 'sql' => 'select name from items where id <= 3 order by id']);
        same([['apple'], ['banana'], ['cherry']], $r['rows']);
        same(false, $r['committed']);
    });

    // Sessions

    test("{$tag} stopping a session leaves it open, and ending it closes it", function () use ($c, $db, $connect, $sessions, $sessionId) {
        $other = $connect(TEST_DATABASE);
        $id = $sessionId($other);
        same(1, $sessions($id), 'the server lists the session the test opened');

        // Nothing runs in it, so stopping its query leaves the session as it is.
        $c->ok('stop', ['db' => $db, 'id' => $id, 'kill' => false]);
        same(1, $sessions($id), 'stopping a query does not end the session');
        same('1', (string) $other->query('select 1')->fetchColumn());

        $c->ok('stop', ['db' => $db, 'id' => $id, 'kill' => true]);

        // The server takes a moment to close it.
        for ($i = 0; $i < 50 && $sessions($id) > 0; $i++) {
            usleep(100000);
        }

        same(0, $sessions($id), 'the server no longer lists the session');
        fails(fn () => $other->query('select 1'));
    });

    test("{$tag} a session that has ended, or that is in another database, is not stopped", function () use ($c, $db, $connect, $driver, $sessionId) {
        $c->refused('stop', ['db' => $db, 'id' => 2000000000, 'kill' => true], 'ended already');
        $c->refused('stop', ['db' => $db, 'kill' => true], 'ended already');

        // The page is open on one database, and that is as far as its power over sessions goes.
        $elsewhere = $connect($driver === 'pgsql' ? 'postgres' : 'mysql');
        $c->refused('stop', ['db' => $db, 'id' => $sessionId($elsewhere), 'kill' => true], 'ended already');
        same('1', (string) $elsewhere->query('select 1')->fetchColumn(), 'the session in the other database is still there');
    });

    // The list of databases, the sidebar layout and signing out

    test("{$tag} the list of databases has a group with the test database in it", function () use ($c, $db, $driver) {
        $r = $c->ok('databases');
        $listed = array_merge(...array_column($r['groups'], 'items'));
        $found = array_values(array_filter($listed, fn ($item) => $item['id'] === $db));

        same(1, count($found), 'the test database is listed once: '.json_encode($r['groups']));
        same([TEST_DATABASE, $driver], [$found[0]['name'], $found[0]['driver']]);

        // The config lists two names, so no other database on the server shows, the system ones least of all.
        foreach ($listed as $item) {
            check(in_array($item['name'], [TEST_DATABASE, TEST_EXTRA_DATABASE], true), "{$item['name']} is not on the list in config.php");
        }

        check(isset($r['settings']['audit_columns']) && isset($r['layout']['groups']), 'the settings and the layout come with the list');
    });

    test("{$tag} the sidebar layout is saved to its file and comes back with the next list, cleaned", function () use ($c, $db) {
        $mine = [
            'groups' => [
                ['id' => 'u:probe', 'label' => 'Probe', 'items' => [$db, $db, 42, '']],
                ['id' => 'not-mine', 'label' => 'A group without the u: id', 'items' => [$db]],
            ],
            'order' => ['u:probe', $db],
            'hidden' => [$db],
            'folded' => ['u:probe' => true],
        ];

        try {
            $saved = $c->ok('layout', ['layout' => $mine])['layout'];
            $onDisk = json_decode((string) file_get_contents($c->server->layout), true);
            $listed = $c->ok('databases')['layout'];

            foreach (['answer' => $saved, 'file' => $onDisk, 'next list' => $listed] as $where => $layout) {
                same([['id' => 'u:probe', 'label' => 'Probe', 'items' => [$db]]], $layout['groups'], "the groups in the {$where}, with the one that is not the user's own and the values that are not ids left out");
                same(['u:probe', $db], $layout['order'], "the order in the {$where}");
                same([$db], $layout['hidden'], "the hidden databases in the {$where}");
                same(['u:probe' => true], (array) $layout['folded'], "the folded groups in the {$where}");
            }
        } finally {
            $c->ok('layout', ['layout' => []]);
        }
    });

    test("{$tag} logging out ends that browser's session and no other", function () use ($c, $db, $signIn) {
        $other = $signIn();
        $other->ok('databases');

        same(['ok' => true], $other->ok('logout'));

        same(401, $other->api('databases')['status'], 'the browser that logged out is signed out');
        same(401, $other->api('rows', ['db' => $db, 'table' => ['name' => 'items']])['status'], 'and cannot read a table either');
        $c->ok('databases');
        $c->ok('rows', ['db' => $db, 'table' => ['name' => 'items']]);
    });

    // Making and dropping databases. The config lists sqlaris_test and one more name, so that is the only one to make.

    test("{$tag} a new database is empty and opens in the page, and is dropped only when its name is typed back", function () use ($c, $db, $connect, $tablesOf, $hasDatabase) {
        $id = explode('/', $db, 2)[0].'/'.TEST_EXTRA_DATABASE;
        same(false, $hasDatabase(TEST_EXTRA_DATABASE), 'the run starts without it');

        $r = $c->ok('create_database', ['db' => $db, 'name' => TEST_EXTRA_DATABASE]);

        same($id, $r['id']);
        same(true, $hasDatabase(TEST_EXTRA_DATABASE));
        same([], $tablesOf($connect(TEST_EXTRA_DATABASE)), 'a new database has no tables');
        same([], $c->ok('tables', ['db' => $id])['tables'], 'the page can open it');
        $c->refused('create_database', ['db' => $db, 'name' => TEST_EXTRA_DATABASE], 'exist');

        $c->refused('drop_database', ['db' => $id, 'confirm' => strtoupper(TEST_EXTRA_DATABASE)], 'Type the database name');
        $c->refused('drop_database', ['db' => $id, 'confirm' => TEST_DATABASE], 'Type the database name');
        $c->refused('drop_database', ['db' => $id], 'Type the database name');
        same(true, $hasDatabase(TEST_EXTRA_DATABASE), 'a wrong name drops nothing');

        $c->ok('drop_database', ['db' => $id, 'confirm' => TEST_EXTRA_DATABASE]);
        same(false, $hasDatabase(TEST_EXTRA_DATABASE));
    });

    test("{$tag} a database the config keeps off the list is neither made nor dropped from here", function () use ($c, $db, $hasDatabase) {
        $name = TEST_DATABASE.'_unlisted';
        $server = explode('/', $db, 2)[0];

        $c->refused('create_database', ['db' => $db, 'name' => $name], 'off the list');
        same(false, $hasDatabase($name), 'it was not made');
        $c->refused('create_database', ['db' => 'nope/x', 'name' => TEST_EXTRA_DATABASE], 'not on the list');
        same(false, $hasDatabase(TEST_EXTRA_DATABASE), 'a database is not made from one that is not on the list either');
        $c->refused('drop_database', ['db' => "{$server}/{$name}", 'confirm' => $name], 'not on the list');
    });

    // Keep this test last. PostgreSQL copies only a database nobody is in, so the viewer ends every other
    // session in the test database first, and that ends $pdo too. What the test reads from the original it
    // reads before the call, and after it the test goes on with connections opened after the call.
    test("{$tag} a database made as a copy has the tables, indexes and rows of the original", function () use ($c, $db, $pdo, $q, $connect, $tablesOf, $indexesOf, $hasDatabase) {
        same(false, $hasDatabase(TEST_EXTRA_DATABASE), 'the run starts without it');
        $tables = $tablesOf($pdo, true);
        check(count($tables) >= 4, 'the fixture tables are there: '.implode(', ', $tables));
        $rows = [];

        foreach ($tables as $table) {
            $rows[$table] = $pdo->query('select * from '.$q($table).' order by 1')->fetchAll(PDO::FETCH_NUM);
        }

        check(in_array('items_name_idx', $indexesOf($pdo, 'items'), true), 'the original has the index the copy is checked for');

        $r = $c->ok('create_database', ['db' => $db, 'name' => TEST_EXTRA_DATABASE, 'copy' => true]);

        same(explode('/', $db, 2)[0].'/'.TEST_EXTRA_DATABASE, $r['id']);
        $copy = $connect(TEST_EXTRA_DATABASE);
        same([], array_diff($tables, $tablesOf($copy, true)), 'every table of the original is in the copy');

        foreach ($tables as $table) {
            same($rows[$table], $copy->query('select * from '.$q($table).' order by 1')->fetchAll(PDO::FETCH_NUM), "{$table} has the same rows in the copy");
        }

        check(in_array('items_name_idx', $indexesOf($copy, 'items'), true), 'the index came along');

        $copy = null;
        $c->ok('drop_database', ['db' => $r['id'], 'confirm' => TEST_EXTRA_DATABASE]);
        same(false, $hasDatabase(TEST_EXTRA_DATABASE));
    });
}

/** The requests that must be refused before any database is touched. */
function http_tests(TestServer $server, string $username, string $password): void
{
    test('api.php answers only POST with the page\'s own header', function () use ($server, $username, $password) {
        $c = new TestClient($server);
        $c->signIn($username, $password);
        same(400, $c->request('GET', '/api.php')['status']);
        same(400, $c->api('databases', [], ['X-Sqlaris' => ''])['status']);
        same(400, $c->request('POST', '/api.php', 'not json', ['X-Sqlaris' => '1'])['status']);
        same(200, $c->api('databases')['status']);
    });

    test('api.php refuses a browser that has not signed in', function () use ($server) {
        $c = new TestClient($server);
        same(401, $c->api('databases')['status']);
    });

    test('a Host header that is not this computer is refused, signed in or not', function () use ($server, $username, $password) {
        $c = new TestClient($server);
        $c->signIn($username, $password);
        same(403, $c->api('databases', [], ['Host' => 'evil.example'])['status']);
        same(403, $c->request('GET', '/', '', ['Host' => 'evil.example'])['status']);
    });

    test('a wrong password or a missing form token does not sign in', function () use ($server, $username, $password) {
        $c = new TestClient($server);
        check(str_contains($c->signIn($username, $password.'x')['body'], 'do not match'), 'wrong password');
        same(401, $c->api('databases')['status']);

        $c = new TestClient($server);
        $c->request('GET', '/');
        $page = $c->request('POST', '/', http_build_query(['username' => $username, 'password' => $password]), ['Content-Type' => 'application/x-www-form-urlencoded']);
        check(str_contains($page['body'], 'form expired'), 'no token');
        same(401, $c->api('databases')['status']);
    });

    test('the router serves the page, the API and assets, and nothing else', function () use ($server) {
        $c = new TestClient($server);

        foreach (['/.env', '/config.php', '/layout.json', '/diagram-views.json', '/src/lib.php', '/assets/../config.php', '/tests/php/run.php'] as $path) {
            same(404, $c->request('GET', $path)['status'], $path);
        }

        same(200, $c->request('GET', '/assets/app.js')['status']);
    });
}
